name: Java CI
on:
    push:
        paths-ignore:
            - '**.md'
    pull_request:
        paths-ignore:
            - '**.md'
jobs:
    test:
        strategy:
            matrix:
                java: [ 8, 11, 17 ]
                os: [ ubuntu-latest ]
            fail-fast: false
            max-parallel: 8

        name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK ${{ matrix.java }}
                uses: actions/setup-java@v3
                with:
                    cache: maven
                    distribution: 'adopt'
                    java-version: ${{ matrix.java }}
            -   name: Build with Maven
                run: mvn -B clean package
